version: "3.1"

services:
    database:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: padarqsis
        volumes:
            - db_data:/var/lib/mysql

    rest1:
        image: openjdk:21-jdk
        volumes:
            - ./target:/app
        ports:
            - "8081:8080"
        working_dir: /app
        command: ["java", "-jar", "springbootrestapi-0.0.1-SNAPSHOT.jar"]
        depends_on:
            - database
        environment:
            MYSQL_HOST: database
            MYSQL_PORT: 3306
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            SERVER_PORT: 8080
    rest2:
        image: openjdk:21-jdk
        volumes:
            - ./target:/app
        ports:
            - "8082:8080"
        working_dir: /app
        command: ["java", "-jar", "springbootrestapi-0.0.1-SNAPSHOT.jar"]
        depends_on:
            - database
        environment:
            MYSQL_HOST: database
            MYSQL_PORT: 3306
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            SERVER_PORT: 8080
    rest3:
        image: openjdk:21-jdk
        volumes:
            - ./target:/app
        ports:
            - "8083:8080"
        working_dir: /app
        command: ["java", "-jar", "springbootrestapi-0.0.1-SNAPSHOT.jar"]
        depends_on:
            - database
        environment:
            MYSQL_HOST: database
            MYSQL_PORT: 3306
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            SERVER_PORT: 8080
volumes:
    db_data:
