version: "3.1"

services:
    database:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: padarqsis
        volumes:
            - db_data:/var/lib/mysql

    app:
        image: openjdk:21-jdk
        volumes:
            - ./target:/app
        working_dir: /app
        command: ["java", "-jar", "springbootrestapi-0.0.1-SNAPSHOT.jar"]
        depends_on:
            - database
        environment:
            MYSQL_HOST: database
            MYSQL_PORT: 3306
            MYSQL_USER: root
            MYSQL_PASSWORD: root
volumes:
    db_data:
